# Read data

In [1]:
import os
import numpy as np
import pandas as pd
import scanpy as sc
import random

## Import  data

In [3]:
os.chdir('..\\Data_after_Imputation')

In [5]:
#Uncomment the desired data set section and run all cells

## RNAMix1Basic
# mydata='RNAMix1Basic_noDR'
# X_counts = pd.read_csv('RNAmix1_original.csv',header=0,index_col=0)
# Labels = pd.read_csv('rnamix1_original_labels.csv',header=0,index_col=0)

##RNAMix2Basic
# mydata='RNAMix2Basic_noDR'
# X_counts = pd.read_csv('RNAmix2_original.csv',header=0,index_col=0)
# Labels = pd.read_csv('rnamix2_original_labels.csv',header=0,index_col=0)

# TMLungBasic
# mydata='TMLungBasic_noDR'
# X_counts = pd.read_csv('lung_tabula_muris_saver.csv',header=0,index_col=0)
# Labels = pd.read_csv('lung_tabula_muris_labels.csv',header=0,index_col=0)

## Beta2Basic 
# mydata='Beta2Basic_noDR'
# X_counts = pd.read_csv('beta_3_4_10_filtered_saver.csv',header=0,index_col=0)
# Labels = pd.read_csv('beta_cell_groups_3_4_10_after_filtering.csv',header=0,index_col=2)
# Labels=Labels[['cluster']]

## TMPancBasic
# mydata='TMPancBasic_noDR'
# X_counts = pd.read_csv('pancreas_tabula_muris_saver.csv',header=0,index_col=0)
# Labels = pd.read_csv('pancreatic_tabula_muris_labels.csv',header=0,index_col=0)

## BaronPancSCT
# mydata='BaronPancSCT_noDR'
# X_counts = pd.read_csv('BaronPancSCT_filtered.csv',header=0,index_col=0)
# Labels = pd.read_csv('pancreatic_num_labels_filtered.csv',header=0,index_col=0)


## PBMC4k BASIC
# mydata='PBMC4kBASIC_noDR'
# X_counts = pd.read_csv('subset_pbmc4k.csv',header=0,index_col=0)
# Labels = pd.read_csv('subset_pbmc4k_labels.csv',header=0,index_col=0)


## CellMixSngSCT
#mydata='CellMixSngSCT_noDR'
#X_counts = pd.read_csv('Cellmix_sng_SCT.csv',header=0,index_col=0)
#Labels = pd.read_csv('cellmix_sng_labels.csv',header=0,index_col=0)

In [6]:
Labels

             x
Lib90_00000  1
Lib90_00002  3
Lib90_00003  1
Lib90_00004  1
Lib90_00005  1
...         ..
Lib90_04026  1
Lib90_04028  5
Lib90_04029  5
Lib90_04048  5
Lib90_04057  3

[3822 rows x 1 columns]

In [157]:
X_counts

,Lib90_00000,Lib90_00002,Lib90_00003,Lib90_00004,Lib90_00005,Lib90_00006,Lib90_00007,Lib90_00008,Lib90_00010,Lib90_00011,...,Lib90_04012,Lib90_04014,Lib90_04017,Lib90_04019,Lib90_04024,Lib90_04026,Lib90_04028,Lib90_04029,Lib90_04048,Lib90_04057
KRT81,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,...,1.386294,1.386294,4.624973,5.669881,1.945910,1.386294,5.187386,4.875197,5.529429,1.945910
LCN2,2.484907,0.000000,2.564949,2.995732,0.000000,0.000000,0.000000,4.276666,0.000000,0.000000,...,1.791759,1.791759,1.098612,1.098612,2.397895,3.988984,1.098612,1.098612,1.098612,1.791759
AKR1B10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,...,1.098612,1.386294,4.204693,5.549076,2.197225,1.098612,3.737670,4.077537,5.351858,1.386294
SAA1,0.000000,0.000000,1.609438,0.693147,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,...,0.693147,0.693147,0.693147,0.693147,1.609438,1.609438,1.609438,0.693147,0.693147,0.693147
S100A9,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.693147,0.693147,0.693147,0.693147,1.386294,0.693147,0.693147,0.693147,0.693147,0.693147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MMP1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
PRKCQ-AS1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.693147,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
PFKFB3,0.693147,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000
LYPD6B,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
CBR1,0.000000,1.945910,0.000000,1.386294,0.693147,0.693147,1.098612,0.000000,1.791759,0.693147,...,1.098612,1.098612,1.098612,2.197225,2.639057,1.609438,1.791759,1.098612,1.791759,2.197225

In [158]:
[g,c]=X_counts.shape
colnames=["cell_" + str(i)  for i in range(1,c+1)]
rownames=["gene_" + str(i)  for i in range(1,g+1)]
X_counts.columns = colnames
X_counts.index=rownames
X_counts = X_counts.T
X_counts

,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,gene_10,...,gene_2991,gene_2992,gene_2993,gene_2994,gene_2995,gene_2996,gene_2997,gene_2998,gene_2999,gene_3000
cell_1,0.000000,2.484907,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.662960,0.000000,...,0.693147,0.0,0.0,3.784190,0.693147,0.0,0.0,0.693147,0.0,0.000000
cell_2,0.000000,0.000000,0.000000,0.000000,1.098612,0.000000,0.000000,0.000000,1.945910,4.043051,...,0.000000,0.0,0.0,3.850148,1.791759,0.0,0.0,0.000000,0.0,1.945910
cell_3,0.000000,2.564949,0.000000,1.609438,0.000000,0.000000,0.000000,1.098612,5.517453,0.000000,...,0.000000,0.0,0.0,4.454347,0.693147,0.0,0.0,0.000000,0.0,0.000000
cell_4,0.000000,2.995732,0.000000,0.693147,0.000000,0.000000,0.000000,0.000000,5.680173,0.000000,...,0.693147,0.0,0.0,4.077537,0.693147,0.0,0.0,0.000000,0.0,1.386294
cell_5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.730100,0.000000,...,0.000000,0.0,0.0,4.110874,0.693147,0.0,0.0,0.000000,0.0,0.693147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cell_3818,1.386294,3.988984,1.098612,1.609438,0.693147,0.693147,0.693147,1.791759,5.572154,0.693147,...,0.000000,0.0,0.0,4.143135,2.302585,0.0,0.0,1.098612,0.0,1.609438
cell_3819,5.187386,1.098612,3.737670,1.609438,0.693147,0.693147,0.693147,3.135494,2.302585,0.693147,...,0.000000,0.0,0.0,4.499810,0.693147,0.0,0.0,0.000000,0.0,1.791759
cell_3820,4.875197,1.098612,4.077537,0.693147,0.693147,0.693147,0.693147,3.637586,2.944439,0.693147,...,0.000000,0.0,0.0,4.219508,0.693147,0.0,0.0,0.000000,0.0,1.098612
cell_3821,5.529429,1.098612,5.351858,0.693147,0.693147,0.693147,0.693147,4.234107,2.639057,0.693147,...,0.000000,0.0,0.0,3.688879,0.693147,0.0,0.0,0.000000,0.0,1.791759
cell_3822,1.945910,1.791759,1.386294,0.693147,0.693147,0.693147,0.693147,1.098612,2.890372,3.465736,...,0.000000,0.0,0.0,4.330733,2.302585,0.0,0.0,0.000000,0.0,2.197225

In [159]:
#Labels=Labels.astype(str)
Labels.index= X_counts.index
Labels.columns= ['Labels']
Labels.shape

(3822, 1)

In [160]:
type(Labels)

pandas.core.frame.DataFrame

In [161]:
adata=sc.AnnData(X = X_counts, obs = Labels)
print(adata)

AnnData object with n_obs Ã— n_vars = 3822 Ã— 3000
    obs: 'Labels'

In [162]:
adata.X

array([[0.       , 2.4849067, 0.       , ..., 0.6931472, 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        1.9459101],
       [0.       , 2.5649493, 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [4.8751974, 1.0986123, 4.0775375, ..., 0.       , 0.       ,
        1.0986123],
       [5.529429 , 1.0986123, 5.351858 , ..., 0.       , 0.       ,
        1.7917595],
       [1.9459101, 1.7917595, 1.3862944, ..., 0.       , 0.       ,
        2.1972246]], dtype=float32)

In [163]:

adata.write(mydata+'.h5ad')

In [164]:
mydata

'CellMixSngSCT_noDR'

# Check that the data can be uploaded

In [14]:
adata= sc.read(mydata+'.h5ad')

In [15]:
adata

AnnData object with n_obs Ã— n_vars = 620 Ã— 2
    obs: 'Labels'